// Copyright (c) Facebook, Inc. and its affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
//
// This file was automatically generated by make_action_space_sources.py.
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Transforms/AggressiveInstCombine/AggressiveInstCombine.h"
#include "llvm/Transforms/Coroutines/CoroCleanup.h"
#include "llvm/Transforms/Coroutines/CoroEarly.h"
#include "llvm/Transforms/Coroutines/CoroElide.h"
#include "llvm/Transforms/IPO/AlwaysInliner.h"
#include "llvm/Transforms/IPO/Annotation2Metadata.h"
#include "llvm/Transforms/IPO/Attributor.h"
#include "llvm/Transforms/IPO/BlockExtractor.h"
#include "llvm/Transforms/IPO/CalledValuePropagation.h"
#include "llvm/Transforms/IPO/ConstantMerge.h"
#include "llvm/Transforms/IPO/CrossDSOCFI.h"
#include "llvm/Transforms/IPO/DeadArgumentElimination.h"
#include "llvm/Transforms/IPO/ElimAvailExtern.h"
#include "llvm/Transforms/IPO/ForceFunctionAttrs.h"
#include "llvm/Transforms/IPO/FunctionAttrs.h"
#include "llvm/Transforms/IPO/FunctionImport.h"
#include "llvm/Transforms/IPO/GlobalDCE.h"
#include "llvm/Transforms/IPO/GlobalOpt.h"
#include "llvm/Transforms/IPO/GlobalSplit.h"
#include "llvm/Transforms/IPO/HotColdSplitting.h"
#include "llvm/Transforms/IPO/IROutliner.h"
#include "llvm/Transforms/IPO/InferFunctionAttrs.h"
#include "llvm/Transforms/IPO/Inliner.h"
#include "llvm/Transforms/IPO/Internalize.h"
#include "llvm/Transforms/IPO/LoopExtractor.h"
#include "llvm/Transforms/IPO/LowerTypeTests.h"
#include "llvm/Transforms/IPO/MergeFunctions.h"
#include "llvm/Transforms/IPO/OpenMPOpt.h"
#include "llvm/Transforms/IPO/PartialInlining.h"
#include "llvm/Transforms/IPO/SCCP.h"
#include "llvm/Transforms/IPO/SampleProfile.h"
#include "llvm/Transforms/IPO/SampleProfileProbe.h"
#include "llvm/Transforms/IPO/StripDeadPrototypes.h"
#include "llvm/Transforms/IPO/StripSymbols.h"
#include "llvm/Transforms/IPO/SyntheticCountsPropagation.h"
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
#include "llvm/Transforms/ObjCARC.h"
#include "llvm/Transforms/Scalar/ADCE.h"
#include "llvm/Transforms/Scalar/AlignmentFromAssumptions.h"
#include "llvm/Transforms/Scalar/AnnotationRemarks.h"
#include "llvm/Transforms/Scalar/BDCE.h"
#include "llvm/Transforms/Scalar/CallSiteSplitting.h"
#include "llvm/Transforms/Scalar/ConstantHoisting.h"
#include "llvm/Transforms/Scalar/ConstraintElimination.h"
#include "llvm/Transforms/Scalar/CorrelatedValuePropagation.h"
#include "llvm/Transforms/Scalar/DCE.h"
#include "llvm/Transforms/Scalar/DFAJumpThreading.h"
#include "llvm/Transforms/Scalar/DeadStoreElimination.h"
#include "llvm/Transforms/Scalar/DivRemPairs.h"
#include "llvm/Transforms/Scalar/EarlyCSE.h"
#include "llvm/Transforms/Scalar/Float2Int.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/GuardWidening.h"
#include "llvm/Transforms/Scalar/InductiveRangeCheckElimination.h"
#include "llvm/Transforms/Scalar/InferAddressSpaces.h"
#include "llvm/Transforms/Scalar/InstSimplifyPass.h"
#include "llvm/Transforms/Scalar/JumpThreading.h"
#include "llvm/Transforms/Scalar/LoopDataPrefetch.h"
#include "llvm/Transforms/Scalar/LoopDistribute.h"
#include "llvm/Transforms/Scalar/LoopFuse.h"
#include "llvm/Transforms/Scalar/LoopLoadElimination.h"
#include "llvm/Transforms/Scalar/LoopSink.h"
#include "llvm/Transforms/Scalar/LoopUnrollPass.h"
#include "llvm/Transforms/Scalar/LowerAtomic.h"
#include "llvm/Transforms/Scalar/LowerConstantIntrinsics.h"
#include "llvm/Transforms/Scalar/LowerExpectIntrinsic.h"
#include "llvm/Transforms/Scalar/LowerGuardIntrinsic.h"
#include "llvm/Transforms/Scalar/LowerMatrixIntrinsics.h"
#include "llvm/Transforms/Scalar/LowerWidenableCondition.h"
#include "llvm/Transforms/Scalar/MakeGuardsExplicit.h"
#include "llvm/Transforms/Scalar/MemCpyOptimizer.h"
#include "llvm/Transforms/Scalar/MergeICmps.h"
#include "llvm/Transforms/Scalar/MergedLoadStoreMotion.h"
#include "llvm/Transforms/Scalar/NaryReassociate.h"
#include "llvm/Transforms/Scalar/NewGVN.h"
#include "llvm/Transforms/Scalar/PartiallyInlineLibCalls.h"
#include "llvm/Transforms/Scalar/Reassociate.h"
#include "llvm/Transforms/Scalar/Reg2Mem.h"
#include "llvm/Transforms/Scalar/RewriteStatepointsForGC.h"
#include "llvm/Transforms/Scalar/SCCP.h"
#include "llvm/Transforms/Scalar/SROA.h"
#include "llvm/Transforms/Scalar/ScalarizeMaskedMemIntrin.h"
#include "llvm/Transforms/Scalar/Scalarizer.h"
#include "llvm/Transforms/Scalar/SeparateConstOffsetFromGEP.h"
#include "llvm/Transforms/Scalar/SimplifyCFG.h"
#include "llvm/Transforms/Scalar/Sink.h"
#include "llvm/Transforms/Scalar/SpeculativeExecution.h"
#include "llvm/Transforms/Scalar/StraightLineStrengthReduce.h"
#include "llvm/Transforms/Scalar/StructurizeCFG.h"
#include "llvm/Transforms/Scalar/TailRecursionElimination.h"
#include "llvm/Transforms/Scalar/WarnMissedTransforms.h"
#include "llvm/Transforms/Utils/AddDiscriminators.h"
#include "llvm/Transforms/Utils/AssumeBundleBuilder.h"
#include "llvm/Transforms/Utils/BreakCriticalEdges.h"
#include "llvm/Transforms/Utils/CanonicalizeAliases.h"
#include "llvm/Transforms/Utils/FixIrreducible.h"
#include "llvm/Transforms/Utils/HelloWorld.h"
#include "llvm/Transforms/Utils/InjectTLIMappings.h"
#include "llvm/Transforms/Utils/InstructionNamer.h"
#include "llvm/Transforms/Utils/LCSSA.h"
#include "llvm/Transforms/Utils/LibCallsShrinkWrap.h"
#include "llvm/Transforms/Utils/LoopSimplify.h"
#include "llvm/Transforms/Utils/LoopVersioning.h"
#include "llvm/Transforms/Utils/LowerInvoke.h"
#include "llvm/Transforms/Utils/LowerSwitch.h"
#include "llvm/Transforms/Utils/Mem2Reg.h"
#include "llvm/Transforms/Utils/MetaRenamer.h"
#include "llvm/Transforms/Utils/NameAnonGlobals.h"
#include "llvm/Transforms/Utils/PredicateInfo.h"
#include "llvm/Transforms/Utils/RelLookupTableConverter.h"
#include "llvm/Transforms/Utils/StripGCRelocates.h"
#include "llvm/Transforms/Utils/StripNonLineTableDebugInfo.h"
#include "llvm/Transforms/Utils/SymbolRewriter.h"
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
#include "llvm/Transforms/Utils/UnifyLoopExits.h"
#include "llvm/Transforms/Vectorize/LoadStoreVectorizer.h"
#include "llvm/Transforms/Vectorize/LoopVectorize.h"
#include "llvm/Transforms/Vectorize/SLPVectorizer.h"
#include "llvm/Transforms/Vectorize/VectorCombine.h"

llvm::ModulePassManager createActionPipeline(CompilerGymPass action) {
  llvm::ModulePassManager pm;
  switch (action) {
    case CompilerGymPass::ADCEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ADCEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ADD_DISCRIMINATORS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AddDiscriminatorsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::AGGRESSIVE_INST_COMBINE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AggressiveInstCombinePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ALIGNMENT_FROM_ASSUMPTIONS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AlignmentFromAssumptionsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ALWAYS_INLINER_PASS:
      pm.addPass(llvm::AlwaysInlinerPass());
      break;
    case CompilerGymPass::ANNOTATION2METADATA_PASS:
      pm.addPass(llvm::Annotation2MetadataPass());
      break;
    case CompilerGymPass::ANNOTATION_REMARKS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AnnotationRemarksPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ASSUME_BUILDER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AssumeBuilderPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ASSUME_SIMPLIFY_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::AssumeSimplifyPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ATTRIBUTOR_PASS:
      pm.addPass(llvm::AttributorPass());
      break;
    case CompilerGymPass::BDCEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::BDCEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::BLOCK_EXTRACTOR_PASS:
      pm.addPass(llvm::BlockExtractorPass());
      break;
    case CompilerGymPass::BREAK_CRITICAL_EDGES_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::BreakCriticalEdgesPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CALL_SITE_SPLITTING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::CallSiteSplittingPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CALLED_VALUE_PROPAGATION_PASS:
      pm.addPass(llvm::CalledValuePropagationPass());
      break;
    case CompilerGymPass::CANONICALIZE_ALIASES_PASS:
      pm.addPass(llvm::CanonicalizeAliasesPass());
      break;
    case CompilerGymPass::CONSTANT_HOISTING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ConstantHoistingPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CONSTANT_MERGE_PASS:
      pm.addPass(llvm::ConstantMergePass());
      break;
    case CompilerGymPass::CONSTRAINT_ELIMINATION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ConstraintEliminationPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CORO_CLEANUP_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::CoroCleanupPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CORO_EARLY_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::CoroEarlyPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CORO_ELIDE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::CoroElidePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CORRELATED_VALUE_PROPAGATION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::CorrelatedValuePropagationPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::CROSS_DSOCFIPASS:
      pm.addPass(llvm::CrossDSOCFIPass());
      break;
    case CompilerGymPass::DCEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::DCEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::DFAJUMP_THREADING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::DFAJumpThreadingPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::DSEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::DSEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::DEAD_ARGUMENT_ELIMINATION_PASS:
      pm.addPass(llvm::DeadArgumentEliminationPass());
      break;
    case CompilerGymPass::DIV_REM_PAIRS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::DivRemPairsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::EARLY_CSEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::EarlyCSEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::ELIMINATE_AVAILABLE_EXTERNALLY_PASS:
      pm.addPass(llvm::EliminateAvailableExternallyPass());
      break;
    case CompilerGymPass::FIX_IRREDUCIBLE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::FixIrreduciblePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::FLOAT2INT_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::Float2IntPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::FORCE_FUNCTION_ATTRS_PASS:
      pm.addPass(llvm::ForceFunctionAttrsPass());
      break;
    case CompilerGymPass::FUNCTION_IMPORT_PASS:
      pm.addPass(llvm::FunctionImportPass());
      break;
    case CompilerGymPass::FUNCTION_SPECIALIZATION_PASS:
      pm.addPass(llvm::FunctionSpecializationPass());
      break;
    case CompilerGymPass::GVN:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::GVN());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::GVNHOIST_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::GVNHoistPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::GVNSINK_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::GVNSinkPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::GLOBAL_DCEPASS:
      pm.addPass(llvm::GlobalDCEPass());
      break;
    case CompilerGymPass::GLOBAL_OPT_PASS:
      pm.addPass(llvm::GlobalOptPass());
      break;
    case CompilerGymPass::GLOBAL_SPLIT_PASS:
      pm.addPass(llvm::GlobalSplitPass());
      break;
    case CompilerGymPass::GUARD_WIDENING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::GuardWideningPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::HELLO_WORLD_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::HelloWorldPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::HOT_COLD_SPLITTING_PASS:
      pm.addPass(llvm::HotColdSplittingPass());
      break;
    case CompilerGymPass::IPSCCPPASS:
      pm.addPass(llvm::IPSCCPPass());
      break;
    case CompilerGymPass::IRCEPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::IRCEPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::IROUTLINER_PASS:
      pm.addPass(llvm::IROutlinerPass());
      break;
    case CompilerGymPass::INFER_ADDRESS_SPACES_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::InferAddressSpacesPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::INFER_FUNCTION_ATTRS_PASS:
      pm.addPass(llvm::InferFunctionAttrsPass());
      break;
    case CompilerGymPass::INJECT_TLIMAPPINGS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::InjectTLIMappings());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::INST_COMBINE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::InstCombinePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::INST_SIMPLIFY_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::InstSimplifyPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::INSTRUCTION_NAMER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::InstructionNamerPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::INTERNALIZE_PASS:
      pm.addPass(llvm::InternalizePass());
      break;
    case CompilerGymPass::JUMP_THREADING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::JumpThreadingPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LCSSAPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LCSSAPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LIB_CALLS_SHRINK_WRAP_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LibCallsShrinkWrapPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOAD_STORE_VECTORIZER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoadStoreVectorizerPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_DATA_PREFETCH_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopDataPrefetchPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_DISTRIBUTE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopDistributePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_EXTRACTOR_PASS:
      pm.addPass(llvm::LoopExtractorPass());
      break;
    case CompilerGymPass::LOOP_FUSE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopFusePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_LOAD_ELIMINATION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopLoadEliminationPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_SIMPLIFY_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopSimplifyPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_SINK_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopSinkPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_UNROLL_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopUnrollPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_VECTORIZE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopVectorizePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOOP_VERSIONING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LoopVersioningPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_ATOMIC_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerAtomicPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_CONSTANT_INTRINSICS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerConstantIntrinsicsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_EXPECT_INTRINSIC_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerExpectIntrinsicPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_GUARD_INTRINSIC_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerGuardIntrinsicPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_INVOKE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerInvokePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_MATRIX_INTRINSICS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerMatrixIntrinsicsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_SWITCH_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerSwitchPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::LOWER_TYPE_TESTS_PASS:
      pm.addPass(llvm::LowerTypeTestsPass());
      break;
    case CompilerGymPass::LOWER_WIDENABLE_CONDITION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::LowerWidenableConditionPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::MAKE_GUARDS_EXPLICIT_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::MakeGuardsExplicitPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::MEM_CPY_OPT_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::MemCpyOptPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::MERGE_FUNCTIONS_PASS:
      pm.addPass(llvm::MergeFunctionsPass());
      break;
    case CompilerGymPass::MERGE_ICMPS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::MergeICmpsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::MERGED_LOAD_STORE_MOTION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::MergedLoadStoreMotionPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::META_RENAMER_PASS:
      pm.addPass(llvm::MetaRenamerPass());
      break;
    case CompilerGymPass::MODULE_INLINER_WRAPPER_PASS:
      pm.addPass(llvm::ModuleInlinerWrapperPass());
      break;
    case CompilerGymPass::NAME_ANON_GLOBAL_PASS:
      pm.addPass(llvm::NameAnonGlobalPass());
      break;
    case CompilerGymPass::NARY_REASSOCIATE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::NaryReassociatePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::NEW_GVNPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::NewGVNPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::OBJ_CARCAPELIM_PASS:
      pm.addPass(llvm::ObjCARCAPElimPass());
      break;
    case CompilerGymPass::OBJ_CARCCONTRACT_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ObjCARCContractPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::OBJ_CARCEXPAND_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ObjCARCExpandPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::OBJ_CARCOPT_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ObjCARCOptPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::OPEN_MPOPT_PASS:
      pm.addPass(llvm::OpenMPOptPass());
      break;
    case CompilerGymPass::PARTIAL_INLINER_PASS:
      pm.addPass(llvm::PartialInlinerPass());
      break;
    case CompilerGymPass::PARTIALLY_INLINE_LIB_CALLS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::PartiallyInlineLibCallsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::PREDICATE_INFO_VERIFIER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::PredicateInfoVerifierPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::PROMOTE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::PromotePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::PSEUDO_PROBE_UPDATE_PASS:
      pm.addPass(llvm::PseudoProbeUpdatePass());
      break;
    case CompilerGymPass::REASSOCIATE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ReassociatePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::REDUNDANT_DBG_INST_ELIMINATION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::RedundantDbgInstEliminationPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::REG_TO_MEM_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::RegToMemPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::REL_LOOKUP_TABLE_CONVERTER_PASS:
      pm.addPass(llvm::RelLookupTableConverterPass());
      break;
    case CompilerGymPass::REVERSE_POST_ORDER_FUNCTION_ATTRS_PASS:
      pm.addPass(llvm::ReversePostOrderFunctionAttrsPass());
      break;
    case CompilerGymPass::REWRITE_STATEPOINTS_FOR_GC:
      pm.addPass(llvm::RewriteStatepointsForGC());
      break;
    case CompilerGymPass::REWRITE_SYMBOL_PASS:
      pm.addPass(llvm::RewriteSymbolPass());
      break;
    case CompilerGymPass::SCCPPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SCCPPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SLPVECTORIZER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SLPVectorizerPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SROA:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SROA());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SAMPLE_PROFILE_LOADER_PASS:
      pm.addPass(llvm::SampleProfileLoaderPass());
      break;
    case CompilerGymPass::SCALARIZE_MASKED_MEM_INTRIN_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ScalarizeMaskedMemIntrinPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SCALARIZER_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::ScalarizerPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SEPARATE_CONST_OFFSET_FROM_GEPPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SeparateConstOffsetFromGEPPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SIMPLIFY_CFGPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SimplifyCFGPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SINKING_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SinkingPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SPECULATIVE_EXECUTION_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::SpeculativeExecutionPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::STRAIGHT_LINE_STRENGTH_REDUCE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::StraightLineStrengthReducePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::STRIP_DEAD_DEBUG_INFO_PASS:
      pm.addPass(llvm::StripDeadDebugInfoPass());
      break;
    case CompilerGymPass::STRIP_DEAD_PROTOTYPES_PASS:
      pm.addPass(llvm::StripDeadPrototypesPass());
      break;
    case CompilerGymPass::STRIP_DEBUG_DECLARE_PASS:
      pm.addPass(llvm::StripDebugDeclarePass());
      break;
    case CompilerGymPass::STRIP_GCRELOCATES:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::StripGCRelocates());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::STRIP_NON_DEBUG_SYMBOLS_PASS:
      pm.addPass(llvm::StripNonDebugSymbolsPass());
      break;
    case CompilerGymPass::STRIP_NON_LINE_TABLE_DEBUG_INFO_PASS:
      pm.addPass(llvm::StripNonLineTableDebugInfoPass());
      break;
    case CompilerGymPass::STRIP_SYMBOLS_PASS:
      pm.addPass(llvm::StripSymbolsPass());
      break;
    case CompilerGymPass::STRUCTURIZE_CFGPASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::StructurizeCFGPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::SYNTHETIC_COUNTS_PROPAGATION:
      pm.addPass(llvm::SyntheticCountsPropagation());
      break;
    case CompilerGymPass::TAIL_CALL_ELIM_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::TailCallElimPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::UNIFY_FUNCTION_EXIT_NODES_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::UnifyFunctionExitNodesPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::UNIFY_LOOP_EXITS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::UnifyLoopExitsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::VECTOR_COMBINE_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::VectorCombinePass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::WARN_MISSED_TRANSFORMATIONS_PASS:
      llvm::FunctionPassManager fpm;
      fpm.addPass(llvm::WarnMissedTransformationsPass());
      pm.addPass(createModuleToFunctionPassAdaptor(std::move(fpm)));
      break;
    case CompilerGymPass::WHOLE_PROGRAM_DEVIRT_PASS:
      pm.addPass(llvm::WholeProgramDevirtPass());
      break;
      return pm;
  }
