// Copyright (c) Facebook, Inc. and its affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
//
// This file was automatically generated by make_action_space_sources.py.
#include "llvm/Passes/PassBuilder.h"

llvm::ModulePassManager createPassManagerFromAction(CompilerGymPass action);
void addActionToPassManager(CompilerGymPass action, llvm::ModulePassManager& pm);
