---
name: compiler_gym
channels:
    - conda-forge
dependencies:
    - boost-cpp=1.73.0
    - cmake=3.22.1
    - fmt=7.1.3
    - grpc-cpp=1.46.1
    - libprotobuf=3.19.6
    - llvm=10.0.0
    - ninja=1.10.2
    - nlohmann_json=3.10.5
    - pip
    - pkg-config=0.29.2
    - python=3.10
